name: Android CI (release)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with gradle
        run: chmod +x ./gradlew && ./gradlew clean :app:assembleRelease

      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
